name: Deploy to Railway
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]

jobs:
  deploy:
    env:
      IMAGEKITIO_URL: ${{ secrets.IMAGEKITIO_URL }}
      IMAGEKITIO_PUBLIC_KEY: ${{ secrets.IMAGEKITIO_PUBLIC_KEY }}
      IMAGEKITIO_PRIVATE_KEY: ${{ secrets.IMAGEKITIO_PRIVATE_KEY }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install packages
        run: npm install

      - name: Start dev server
        run: npm run dev

      - name: Run test
        run: npm run test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service binar-be-challenge-ch6
